apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canary-app-helm.fullname" . }}-nginx
data:
  default.conf: |
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        location /config/version {
            default_type text/plain;
            alias /etc/demo-app/version;
        }
    }
