apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "canary-app-helm.fullname" . }}-ingress-canary
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "0"
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /canary
        pathType: Prefix
        backend:
          service:
            name: {{ include "canary-app-helm.fullname" . }}-canary
            port:
              number: 80
