apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "canary-app-helm.fullname" . }}-canary-ingress
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "0"
  labels:
    {{- include "canary-app-helm.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "canary-app-helm.fullname" . }}-canary
            port:
              number: {{ .Values.service.port }}
