apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "canary-app-helm.fullname" . }}
  labels:
    {{- include "canary-app-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      {{- include "canary-app-helm.selectorLabels" . | nindent 6 }}
  strategy:
    canary:
      canaryService: {{ include "canary-app-helm.fullname" . }}-canary
      stableService: {{ include "canary-app-helm.fullname" . }}-stable
      trafficRouting:
        nginx:
          stableIngress: {{ include "canary-app-helm.fullname" . }}-ingress
      steps:
      - setWeight: 0
      - pause: {}  # Pause to test new version
      - setWeight: 10
      - pause: {}  # Pause to test new version
      - setWeight: 50
      - pause: {}  # Pause to test new version
      - setWeight: 100
  template:
    metadata:
      labels:
        app: {{ include "canary-app-helm.fullname" . }}
        {{- include "canary-app-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: demo-app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
